name: Publish

on:
  push:
    tags: ['v*']

jobs:
  publish:
    if: github.repository == 'brc-dd/prettier-plugin-vitepress'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: https://registry.npmjs.org
      - uses: denoland/setup-deno@v2
      - run: deno task build --minify ${GITHUB_REF#refs/tags/v}
      - run: cd dist && pnpm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
